[2024-01-23T12:55:12.194+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Python_dag.run_python scheduled__2024-01-22T00:00:00+00:00 [queued]>
[2024-01-23T12:55:12.235+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Python_dag.run_python scheduled__2024-01-22T00:00:00+00:00 [queued]>
[2024-01-23T12:55:12.237+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-01-23T12:55:12.272+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): run_python> on 2024-01-22 00:00:00+00:00
[2024-01-23T12:55:12.280+0000] {standard_task_runner.py:60} INFO - Started process 193 to run task
[2024-01-23T12:55:12.293+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Python_dag', 'run_python', 'scheduled__2024-01-22T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmp3cttqwgv']
[2024-01-23T12:55:12.299+0000] {standard_task_runner.py:88} INFO - Job 97: Subtask run_python
[2024-01-23T12:55:12.440+0000] {task_command.py:423} INFO - Running <TaskInstance: Python_dag.run_python scheduled__2024-01-22T00:00:00+00:00 [running]> on host 48444e3206b7
[2024-01-23T12:55:12.800+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rhon' AIRFLOW_CTX_DAG_ID='Python_dag' AIRFLOW_CTX_TASK_ID='run_python' AIRFLOW_CTX_EXECUTION_DATE='2024-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-22T00:00:00+00:00'
[2024-01-23T12:55:12.852+0000] {logging_mixin.py:188} INFO - Good morning Akello, its 9 already
[2024-01-23T12:55:12.857+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-23T12:55:12.898+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Python_dag, task_id=run_python, execution_date=20240122T000000, start_date=20240123T125512, end_date=20240123T125512
[2024-01-23T12:55:12.997+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T12:55:13.048+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
