[2024-01-23T12:55:12.242+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Python_dag.run_python scheduled__2024-01-21T00:00:00+00:00 [queued]>
[2024-01-23T12:55:12.270+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Python_dag.run_python scheduled__2024-01-21T00:00:00+00:00 [queued]>
[2024-01-23T12:55:12.272+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-01-23T12:55:12.313+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): run_python> on 2024-01-21 00:00:00+00:00
[2024-01-23T12:55:12.320+0000] {standard_task_runner.py:60} INFO - Started process 195 to run task
[2024-01-23T12:55:12.331+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Python_dag', 'run_python', 'scheduled__2024-01-21T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/python_dag.py', '--cfg-path', '/tmp/tmptudcz8ma']
[2024-01-23T12:55:12.346+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask run_python
[2024-01-23T12:55:12.500+0000] {task_command.py:423} INFO - Running <TaskInstance: Python_dag.run_python scheduled__2024-01-21T00:00:00+00:00 [running]> on host 48444e3206b7
[2024-01-23T12:55:12.851+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rhon' AIRFLOW_CTX_DAG_ID='Python_dag' AIRFLOW_CTX_TASK_ID='run_python' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-21T00:00:00+00:00'
[2024-01-23T12:55:12.902+0000] {logging_mixin.py:188} INFO - Good morning Akello, its 9 already
[2024-01-23T12:55:12.912+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-23T12:55:12.942+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Python_dag, task_id=run_python, execution_date=20240121T000000, start_date=20240123T125512, end_date=20240123T125512
[2024-01-23T12:55:12.999+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T12:55:13.064+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
